name: api_manager
description: API Manager.
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dartz: ^0.10.0-nullsafety.2
  dio: ^4.0.0
  equatable: ^2.0.3
  pretty_dio_logger: ^1.2.0-beta-1

dev_dependencies:
  lint: ^1.5.3
  test: ^1.17.11

flutter: null
